### ISSUE TITLE
Minor Request: Table of Boss Themes

### ISSUE THREAD

**Issue by n-jones0** [SpaceBoiStreams/KH2-Separate-OrgXIII-SpecialBoss-OSTs#1]
Just a minor request, and for the github readme and not the actual pack:

It would be great if the readme had a table breaking down what new themes go where. (Also, the way the readme is set up it currently doesn't display automatically when looking at the repository root, have to click into it.)

**Comment by SpaceBoiStreams** [comment]
I gotcha! I was dead tired and for some reason didn't think of that initially but it shall be added to the main page!

**Comment by SpaceBoiStreams** [comment]
And donezo! Hope that clears everything up! Please enjoy the mod!
